unit TestTarefa3;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, controller.projeto, commons.types, controller.interfaces,
  model.projeto, system.SysUtils;

type
  // Test methods for class TControllerProjeto

  TestTControllerProjeto = class(TTestCase)
  strict private
  public
  published
    procedure TestgetTotal;
    procedure TestgetTotalDivisoes;
    procedure TestloadData;
  end;

implementation

procedure TestTControllerProjeto.TestgetTotal;
var
  ReturnValue: Currency;
  aDataSet: TCommonClientDataSet;
begin
  aDataSet := TCommonClientDataSet.Create(nil);

  try
    TControllerProjeto
      .new
      .loadData(aDataSet);

    ReturnValue := TControllerProjeto
                    .new
                    .getTotal(aDataSet);


    CheckEquals(550, ReturnValue, 'A função de somar os projetos falhou.');
  finally
    if aDataSet <> nil then
      freeandnil(aDataSet);
  end;
end;

procedure TestTControllerProjeto.TestgetTotalDivisoes;
var
  ReturnValue: Currency;
  aDataSet: TCommonClientDataSet;
begin

  aDataSet := TCommonClientDataSet.Create(nil);

  try
    TControllerProjeto
      .new
      .loadData(aDataSet);

    ReturnValue := TControllerProjeto
                    .new
                    .getTotalDivisoes(aDataSet);


    CheckEquals(11.829, ReturnValue, 'A função de divisões os projetos falhou.');
  finally
    if aDataSet <> nil then
      freeandnil(aDataSet);
  end;
end;

procedure TestTControllerProjeto.TestloadData;
var
  ReturnValue: iControllerProjeto;
  aDataSet: TCommonClientDataSet;
begin
    aDataSet := TCommonClientDataSet.Create(nil);

  try
    TControllerProjeto
      .new
      .loadData(aDataSet);

    CheckEquals(10, aDataSet.RecordCount, 'A função de carregar os projetos falhou.');
  finally
    if aDataSet <> nil then
      freeandnil(aDataSet);
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTControllerProjeto.Suite);
end.

