unit TestTarefa1;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, FireDAC.Comp.Client, System.SysUtils, uspQuery, System.Classes;

type
  // Test methods for class TspQuery

  TestTspQuery = class(TTestCase)
  strict private
    FspQuery: TspQuery;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGeraSQL;
  end;

implementation

procedure TestTspQuery.SetUp;
begin
  FspQuery := TspQuery.Create(nil);
end;

procedure TestTspQuery.TearDown;
begin
  if FspQuery <> nil then
  begin
    FspQuery.Close;
    freeandnil(FspQuery);
  end;
end;

procedure TestTspQuery.TestGeraSQL;
begin

  FspQuery.LimpaPropriedades;
  FspQuery.spColunas.Add('col1');
  FspQuery.spColunas.Add('col2');
  FspQuery.spTabelas.Add('tab1');
  FspQuery.spCondicoes.Add('col1 = 1');
  CheckException(FspQuery.GeraSQL,nil,'A consulta na tabela falhou');

  FspQuery.LimpaPropriedades;
  FspQuery.spColunas.Add('');
  FspQuery.spTabelas.Add('');
  FspQuery.spCondicoes.Add('');
  CheckException(FspQuery.GeraSQL,nil,'A consulta na tabela falhou');

  FspQuery.LimpaPropriedades;
  FspQuery.spColunas.Add('');
  FspQuery.spTabelas.Add('tab1');
  FspQuery.spTabelas.Add('tab2');
  FspQuery.spCondicoes.Add('');
  CheckException(FspQuery.GeraSQL,nil,'A consulta na tabela falhou');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTspQuery.Suite);
end.

